[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@risc0/=lib/risc0-ethereum/contracts/src/",
    "@solady/=lib/solady/src/",
    "@sp1-contracts/=lib/sp1-contracts/contracts/src/",
    "@risc0-ethereum/=lib/risc0-ethereum/contracts/src",
    "openzeppelin/=lib/openzeppelin-contracts"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
fs_permissions = [{ access = "read", path = "samples"}, { access = "readwrite", path = "deployments" }]
