name: Build and Publish Nitro CLI Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to use for the image (default: latest)'
        required: false
        default: 'latest'

jobs:
  publish-nitro-cli:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write

    env:
      NITRO_CLI_IMAGE: public.ecr.aws/d4t4u8d2/sparsity-ai/nitro-cli

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::004118891089:role/Github-Workflow-Publish-AWS-ECR

      - name: Login to Amazon ECR Public
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Build and Push Nitro CLI Image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/nitro-cli.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.NITRO_CLI_IMAGE }}:${{ github.event.inputs.tag }}

      - name: Generate SLSA provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.NITRO_CLI_IMAGE }}
          subject-digest: ${{ steps.build-image.outputs.digest }}
          push-to-registry: true
